/RMG/Manager/Logging/LogLevel summary

#/tracking/verbose 2

/RMG/Processes/OpticalPhysics true
/RMG/Processes/HadronicPhysics Shielding
/RMG/Processes/ThermalScattering 1
/RMG/Processes/UseGrabmayrsGammaCascades true

/RMG/Output/ActivateOutputScheme IsotopeOutputScheme

/RMG/GrabmayrGammaCascades/SetGammaCascadeFile 64 155 GammaCascades/156Gd-100Entries.txt
/RMG/GrabmayrGammaCascades/SetGammaCascadeRandomStartLocation 1
/RMG/GrabmayrGammaCascades/SetGammaCascadeFile 64 157 GammaCascades/158Gd-100Entries.txt
/run/initialize


/RMG/Output/NtuplePerDetector false
/RMG/Output/FileName build/Custom.csv

/RMG/Generator/Select GPS
/gps/particle mu-
/gps/ang/type iso
/gps/energy 10 GeV

#/RMG/Processes/Realm CosmicRays


/run/beamOn 1
