/RMG/Manager/Logging/LogLevel summary

#/tracking/verbose 1

/RMG/Processes/OpticalPhysics true
/RMG/Output/ActivateOutputScheme IsotopeFilter
/run/initialize

#/process/optical/boundary/verbose 2

/RMG/Output/IsotopeFilter/AddIsotope 77 32
/RMG/Output/IsotopeFilter/DiscardPhotonsIfIsotopeNotProduced true
/RMG/Output/NtuplePerDetector false

/RMG/Generator/Confine UnConfined
/RMG/Generator/Select MUSUNCosmicMuons

/RMG/Generator/MUSUNCosmicMuons/SetMUSUNFile musun/MUSUN_100_events.csv

/run/beamOn 100