/RMG/Manager/Logging/LogLevel summary

/tracking/verbose 2

/RMG/Processes/HadronicPhysics Shielding
/RMG/Processes/Realm CosmicRays
/RMG/Processes/UseGrabmayrsGammaCascades true

/RMG/GrabmayrGammaCascades/SetGammaCascadeFile 64 155 gammacascades/156Gd-5keV-cascades.dat
/RMG/GrabmayrGammaCascades/SetGammaCascadeFile 64 157 gammacascades/158Gd-5keV-cascades.dat

/RMG/Processes/OpticalPhysics true
#/RMG/Output/ActivateOutputScheme IsotopeOutputScheme
/run/initialize

/process/optical/boundary/verbose 2

/RMG/Output/NtuplePerDetector false
/RMG/Generator/Confine UnConfined

/RMG/Generator/Select GPS
/gps/particle opticalphoton
/gps/energy 3 eV
/gps/position 3900 0 0 mm
/gps/ang/type iso

/run/beamOn 100000