/RMG/Manager/Logging/LogLevel summary

#/tracking/verbose 1

/RMG/Processes/OpticalPhysics true
/RMG/Processes/HadronicPhysics Shielding
/RMG/Processes/ThermalScattering 1
/RMG/Output/ActivateOutputScheme IsotopeFilter
/run/initialize

/RMG/Output/IsotopeFilter/AddIsotope 77 32
/RMG/Output/IsotopeFilter/DiscardPhotonsIfIsotopeNotProduced true
/RMG/Output/NtuplePerDetector false

/RMG/Generator/Select GPS
/gps/particle neutron
/gps/ang/type iso
/gps/energy 0.5 MeV

#/RMG/Processes/Realm CosmicRays

/run/beamOn 100
