/RMG/Output/FileName output.hdf5

/RMG/Geometry/RegisterDetector Germanium HPGe1 0
/RMG/Geometry/RegisterDetector Germanium HPGe2 1
/RMG/Geometry/RegisterDetector Germanium HPGe3 2
/RMG/Geometry/RegisterDetector Germanium HPGe4 3

/run/initialize

/RMG/Generator/Select GPS
/gps/particle gamma
/gps/ang/type iso
/gps/ang/mintheta 0 deg
/gps/ang/maxtheta 60 deg
/gps/position 0 0 10 cm
/gps/energy 10 MeV

/run/beamOn 1000000